import { Marcellus, Monsterrat } from "next/font/local";
import "./globals.css";

const marcellus = Marcellus({
  subsets: ["latin"],
  variable: "--font-marcellus",
  weight: "400",
});
const monsterrat = Monsterrat({
  subsets: ["latin"],
  variable: "--font-monsterrat",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body
        className={`${marcellus.variable} ${monsterrat.variable} `}
      >
        {children}
      </body>
    </html>
  );
}
